/* ****** Predefined skill categories for the profile multi-select ****** */

export interface SkillCategory {
  id: string;
  label: string;
  skills: string[];
}

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    id: "languages",
    label: "Programming Languages",
    skills: [
      "Python",
      "JavaScript",
      "TypeScript",
      "Java",
      "C",
      "C++",
      "C#",
      "Go",
      "Rust",
      "Ruby",
      "PHP",
      "Swift",
      "Kotlin",
      "Scala",
      "R",
      "Dart",
      "Elixir",
      "Haskell",
      "Lua",
      "Perl",
      "MATLAB",
    ],
  },
  {
    id: "frontend",
    label: "Frontend",
    skills: [
      "React",
      "Next.js",
      "Vue.js",
      "Angular",
      "Svelte",
      "HTML",
      "CSS",
      "Tailwind CSS",
      "SASS/SCSS",
      "Bootstrap",
      "Material UI",
      "Chakra UI",
      "Shadcn UI",
      "Redux",
      "Zustand",
      "React Query",
      "GraphQL",
      "Webpack",
      "Vite",
      "Storybook",
    ],
  },
  {
    id: "backend",
    label: "Backend",
    skills: [
      "Node.js",
      "Express.js",
      "FastAPI",
      "Django",
      "Flask",
      "Spring Boot",
      "NestJS",
      "Laravel",
      "Rails",
      "Gin",
      "Fiber",
      "tRPC",
      "REST APIs",
      "gRPC",
      "WebSockets",
      "Hono",
      "Actix",
    ],
  },
  {
    id: "databases",
    label: "Databases",
    skills: [
      "PostgreSQL",
      "MySQL",
      "MongoDB",
      "Redis",
      "SQLite",
      "Elasticsearch",
      "Cassandra",
      "DynamoDB",
      "Supabase",
      "Firebase",
      "Prisma",
      "TypeORM",
      "Drizzle ORM",
      "SQL",
    ],
  },
  {
    id: "devops",
    label: "DevOps & Cloud",
    skills: [
      "Docker",
      "Kubernetes",
      "AWS",
      "GCP",
      "Azure",
      "Terraform",
      "CI/CD",
      "GitHub Actions",
      "Jenkins",
      "Nginx",
      "Linux",
      "Bash",
      "Ansible",
      "Helm",
      "Vercel",
      "Netlify",
      "Cloudflare",
    ],
  },
  {
    id: "tools",
    label: "Tools & Platforms",
    skills: [
      "Git",
      "GitHub",
      "GitLab",
      "Jira",
      "Figma",
      "VS Code",
      "Postman",
      "Notion",
      "npm",
      "pnpm",
      "Yarn",
      "ESLint",
      "Jest",
      "Cypress",
      "Playwright",
      "Vitest",
      "Turborepo",
    ],
  },
  {
    id: "ai_ml",
    label: "AI & Machine Learning",
    skills: [
      "TensorFlow",
      "PyTorch",
      "scikit-learn",
      "Pandas",
      "NumPy",
      "OpenCV",
      "Hugging Face",
      "LangChain",
      "OpenAI API",
      "LLMs",
      "RAG",
      "Computer Vision",
      "NLP",
      "Data Analysis",
      "Mastra",
    ],
  },
  {
    id: "mobile",
    label: "Mobile",
    skills: [
      "React Native",
      "Flutter",
      "iOS Development",
      "Android Development",
      "Expo",
      "Capacitor",
      "Ionic",
    ],
  },
  {
    id: "soft",
    label: "Soft Skills",
    skills: [
      "Leadership",
      "Communication",
      "Problem Solving",
      "Teamwork",
      "Project Management",
      "Agile",
      "Scrum",
      "Mentoring",
      "Public Speaking",
      "Critical Thinking",
      "Time Management",
    ],
  },
];

/* ****** Flat list of all skill names for fuzzy search ****** */
export const ALL_SKILLS: string[] = SKILL_CATEGORIES.flatMap((c) => c.skills);
